language: c

sudo: false

addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam

script: bash -ex .travis-ci.sh

env:
  - OPAM_SWITCH=4.02.3

cache:
  directories:
  - $HOME/.opam
